export const WILAYAS = [
  { code: '01', name: 'أدرار', name_fr: 'Adrar' },
  { code: '02', name: 'الشلف', name_fr: 'Chlef' },
  { code: '03', name: 'الأغواط', name_fr: 'Laghouat' },
  { code: '04', name: 'أم البواقي', name_fr: 'Oum El Bouaghi' },
  { code: '05', name: 'باتنة', name_fr: 'Batna' },
  { code: '06', name: 'بجاية', name_fr: 'Béjaïa' },
  { code: '07', name: 'بسكرة', name_fr: 'Biskra' },
  { code: '08', name: 'بشار', name_fr: 'Béchar' },
  { code: '09', name: 'البليدة', name_fr: 'Blida' },
  { code: '10', name: 'البويرة', name_fr: 'Bouira' },
  { code: '11', name: 'تمنراست', name_fr: 'Tamanrasset' },
  { code: '12', name: 'تبسة', name_fr: 'Tébessa' },
  { code: '13', name: 'تلمسان', name_fr: 'Tlemcen' },
  { code: '14', name: 'تيارت', name_fr: 'Tiaret' },
  { code: '15', name: 'تيزي وزو', name_fr: 'Tizi Ouzou' },
  { code: '16', name: 'الجزائر', name_fr: 'Alger' },
  { code: '17', name: 'الجلفة', name_fr: 'Djelfa' },
  { code: '18', name: 'جيجل', name_fr: 'Jijel' },
  { code: '19', name: 'سطيف', name_fr: 'Sétif' },
  { code: '20', name: 'سعيدة', name_fr: 'Saïda' },
  { code: '21', name: 'سكيكدة', name_fr: 'Skikda' },
  { code: '22', name: 'سيدي بلعباس', name_fr: 'Sidi Bel Abbès' },
  { code: '23', name: 'عنابة', name_fr: 'Annaba' },
  { code: '24', name: 'قالمة', name_fr: 'Guelma' },
  { code: '25', name: 'قسنطينة', name_fr: 'Constantine' },
  { code: '26', name: 'المدية', name_fr: 'Médéa' },
  { code: '27', name: 'مستغانم', name_fr: 'Mostaganem' },
  { code: '28', name: 'المسيلة', name_fr: "M'Sila" },
  { code: '29', name: 'معسكر', name_fr: 'Mascara' },
  { code: '30', name: 'ورقلة', name_fr: 'Ouargla' },
  { code: '31', name: 'وهران', name_fr: 'Oran' },
  { code: '32', name: 'البيض', name_fr: 'El Bayadh' },
  { code: '33', name: 'إليزي', name_fr: 'Illizi' },
  { code: '34', name: 'برج بوعريريج', name_fr: 'Bordj Bou Arréridj' },
  { code: '35', name: 'بومرداس', name_fr: 'Boumerdès' },
  { code: '36', name: 'الطارف', name_fr: 'El Tarf' },
  { code: '37', name: 'تندوف', name_fr: 'Tindouf' },
  { code: '38', name: 'تيسمسيلت', name_fr: 'Tissemsilt' },
  { code: '39', name: 'الوادي', name_fr: 'El Oued' },
  { code: '40', name: 'خنشلة', name_fr: 'Khenchela' },
  { code: '41', name: 'سوق أهراس', name_fr: 'Souk Ahras' },
  { code: '42', name: 'تيبازة', name_fr: 'Tipaza' },
  { code: '43', name: 'ميلة', name_fr: 'Mila' },
  { code: '44', name: 'عين الدفلى', name_fr: 'Aïn Defla' },
  { code: '45', name: 'النعامة', name_fr: 'Naâma' },
  { code: '46', name: 'عين تيموشنت', name_fr: 'Aïn Témouchent' },
  { code: '47', name: 'غرداية', name_fr: 'Ghardaïa' },
  { code: '48', name: 'غليزان', name_fr: 'Relizane' },
  { code: '49', name: 'تيميمون', name_fr: 'Timimoun' },
  { code: '50', name: 'برج باجي مختار', name_fr: 'Bordj Badji Mokhtar' },
  { code: '51', name: 'أولاد جلال', name_fr: 'Ouled Djellal' },
  { code: '52', name: 'بني عباس', name_fr: 'Beni Abbès' },
  { code: '53', name: 'عين صالح', name_fr: 'In Salah' },
  { code: '54', name: 'عين قزام', name_fr: 'In Guezzam' },
  { code: '55', name: 'تقرت', name_fr: 'Touggourt' },
  { code: '56', name: 'جانت', name_fr: 'Djanet' },
  { code: '57', name: 'المغير', name_fr: "El M'Ghair" },
  { code: '58', name: 'المنيعة', name_fr: 'El Menia' },
]
